quarkus.native.resources.includes=META-INF/services/io.debezium.connector.jdbc.dialect.DatabaseDialectProvider

quarkus.native.additional-build-args=\
  --initialize-at-run-time=org.hibernate.type.format.jakartajson.JsonBJsonFormatMapper, \
  --initialize-at-run-time=org.hibernate.type.format.jakartajson.JakartaJsonIntegration, \
  --initialize-at-run-time=org.hibernate.type.format.jackson.JacksonXmlFormatMapper, \
  --initialize-at-run-time=org.hibernate.dialect.OracleOsonJdbcType, \
  --initialize-at-run-time=com.mysql.cj.jdbc.AbandonedConnectionCleanupThread \
  --initialize-at-run-time=io.debezium.connector.jdbc.JdbcSinkConnectorConfig